"""
Self-Healing Module — Shared Data Schemas
All dataclasses, enums, and result types used across the self-healing system.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Any
from datetime import datetime
from playwright.sync_api import Locator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class FailureType(Enum):
    """Categories of test failure."""
    LOCATOR_CHANGE = "LOCATOR_CHANGE"
    TIMING_ISSUE = "TIMING_ISSUE"
    API_SCHEMA_CHANGE = "API_SCHEMA_CHANGE"
    ENVIRONMENT = "ENVIRONMENT"
    DATA_ISSUE = "DATA_ISSUE"
    UNKNOWN = "UNKNOWN"


class RepairStrategy(Enum):
    """Available repair strategies."""
    TEXT_BASED = "TEXT_BASED"
    ATTRIBUTE_BASED = "ATTRIBUTE_BASED"
    AI_BASED = "AI_BASED"
    SELECTOR_FALLBACK = "SELECTOR_FALLBACK"
    INCREASE_WAIT = "INCREASE_WAIT"
    RETRY = "RETRY"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class SafetyMode(Enum):
    """Safety level for repair execution."""
    SAFE = "safe"
    DRY_RUN = "dry_run"
    APPROVAL_REQUIRED = "approval_required"


class HealingPhase(Enum):
    """Phases of the healing pipeline."""
    CLASSIFY = "classify"
    MEMORY_LOOKUP = "memory_lookup"
    REASON = "reason"
    EXECUTE = "execute"
    VALIDATE = "validate"
    RECORD = "record"


# ---------------------------------------------------------------------------
# Element Metadata
# ---------------------------------------------------------------------------

@dataclass
class ElementMetadata:
    """Snapshot of a DOM element's identifying properties."""
    name: str
    selector: str
    tag_name: str = ""
    text: str = ""
    attributes: Dict[str, str] = field(default_factory=dict)
    position: Dict[str, float] = field(default_factory=dict)
    css_classes: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


# ---------------------------------------------------------------------------
# Healing Strategy Results
# ---------------------------------------------------------------------------

@dataclass
class HealingStrategyResult:
    """Result returned by any healing strategy."""
    success: bool
    locator: Optional[Locator] = None
    new_selector: Optional[str] = None
    strategy_name: Optional[str] = None
    confidence: float = 0.0


@dataclass
class HealingResult:
    """Final result of the complete healing pipeline."""
    success: bool
    locator: Optional[Locator] = None
    new_selector: Optional[str] = None
    strategy: Optional[str] = None
    confidence: float = 0.0
    attempts: int = 0
    failure_type: Optional[FailureType] = None
    details: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Failure Classification
# ---------------------------------------------------------------------------

@dataclass
class FailureClassification:
    """Classification output from the ClassifierAgent."""
    failure_type: FailureType
    confidence: float
    reasoning: str
    key_indicators: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Repair Proposal
# ---------------------------------------------------------------------------

@dataclass
class RepairProposal:
    """A proposed repair generated by the ReasonerAgent."""
    strategy: RepairStrategy
    description: str
    proposed_changes: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0
    safety_risk: str = "LOW"


# ---------------------------------------------------------------------------
# Healing Attempt / Report
# ---------------------------------------------------------------------------

@dataclass
class HealingAttempt:
    """Record of a single healing attempt."""
    attempt_id: str
    element_name: str
    original_selector: str
    classification: Optional[FailureClassification] = None
    proposal: Optional[RepairProposal] = None
    result: Optional[HealingStrategyResult] = None
    success: bool = False
    confidence: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class HealingReport:
    """Complete report of a healing operation."""
    element_name: str
    original_selector: str
    attempts: List[HealingAttempt] = field(default_factory=list)
    final_status: str = "FAILED"
    total_attempts: int = 0
    confidence: float = 0.0
    healed_selector: Optional[str] = None
    strategy_used: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


# ---------------------------------------------------------------------------
# Audit Log Entry
# ---------------------------------------------------------------------------

@dataclass
class AuditEntry:
    """Single audit log row."""
    entry_id: str
    timestamp: str
    action: str
    element_name: str
    old_selector: str
    new_selector: Optional[str] = None
    strategy: Optional[str] = None
    confidence: float = 0.0
    success: bool = False
    details: Dict[str, Any] = field(default_factory=dict)
    environment: str = ""
